services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      #- SERVERPORT=51825 #optional
      - PEERS=10 #optional
      - PEERDNS=1.1.1.1 #optional
      - INTERNAL_SUBNET=10.15.15.0 #optional
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 172.18.18.100
    restart: unless-stopped
    networks:
      wireguard-adguard:
        ipv4_address: 172.18.18.10

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    #network_mode: host
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Optional: for DHCP server if desired
      #- "68:68/udp" # Optional: for DHCP server if desired
      - "80:80/tcp" # Web interface
      - "443:443/tcp" # Optional: for HTTPS web interface
      - "3000:3000/tcp" # Optional: for initial setup if port 80 is in use
    volumes:
      - ./adguard-work:/opt/adguardhome/work
      - ./adguard-conf:/opt/adguardhome/conf
    networks:
      wireguard-adguard:
        ipv4_address: 172.18.18.100

networks:
  wireguard-adguard:
    ipam:
      config:
        - subnet: 172.18.18.0/24
